version: 2
registries:
  maven-central:
    type: maven-repository
    url: https://repo.maven.apache.org/maven2
  google:
    type: maven-repository
    url: https://dl.google.com/dl/android/maven2
  gradle:
    type: maven-repository
    url: https://plugins.gradle.org/m2
  intellij:
    type: maven-repository
    url: https://www.jetbrains.com/intellij-repository/releases
  intellij-deps:
    type: maven-repository
    url: https://cache-redirector.jetbrains.com/intellij-dependencies
  kotlin-ide:
    type: maven-repository
    url: https://maven.pkg.jetbrains.space/kotlin/p/kotlin/kotlin-ide-plugin-dependencies/
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "hfhbd"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "hfhbd"
    rebase-strategy: "disabled"
    registries:
      - maven-central
      - google
      - gradle
      - intellij
      - intellij-deps
      - kotlin-ide
