name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      GRADLE_OPTS: -Dorg.gradle.caching=true

    steps:
      - run: kotlin --version
