name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      GRADLE_OPTS: -Dorg.gradle.caching=true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 21
      - uses: gradle/action/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
      - run: ./gradlew assemble compileTestKotlin
      - name: Build with Gradle
        run: ./gradlew build
