name: Release

on:
  release:
    types: [created]

concurrency:
  group: "cd"
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      GRADLE_OPTS: -Dorg.gradle.caching=true

    steps:
      - name: Set environment for version
        run: long="${{ github.ref }}"; version=${long#"refs/tags/v"}; echo "version=${version}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 21
      - uses: gradle/gradle-build-action@v3
      - run: ./gradlew assemble compileTestKotlin
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish
        run: ./gradlew -Pversion=$version --no-configuration-cache publish closeAndReleaseStagingRepository
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONARTYPE_APIKEY }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONARTYPE_APITOKEN }}
